# --- Fuente ---
font_family      CaskaydiaCove Nerd Font Mono
font_size        11.0

# --- Apariencia ---
include theme.conf
background_opacity   0.75
window_padding_width 10
cursor_shape         beam
cursor_blink_interval 0

# --- Comodidad ---
enable_audio_bell      no
confirm_os_window_close 0
scrollback_lines       5000

shell /usr/bin/zsh
