general {
    lock_cmd = pidof hyprlock || ~/scripts/lock.sh
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Baja el brillo a los 2,5 min
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Apaga la pantalla a los 5,5 min (NO bloquea, el teclado de la laptop esta apagado)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# Suspende a los 30 min
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}

# Para bloquear solo por inactividad, agregar:
# listener {
#     timeout = 300
#     on-timeout = loginctl lock-session
# }
