general {
    lock_cmd = pidof hyprlock || ~/scripts/lock.sh
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Para bloquear solo por inactividad, agregar:
# listener {
#     timeout = 300
#     on-timeout = loginctl lock-session
# }
